services:
  # =========================================================================
  # Godavari Bank Spring Boot Backend Web Service on Render
  # =========================================================================
  - type: web
    name: godavari-bank-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: singapore
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        value: jdbc:mysql://mysql-2b7feb4e-mohanboddu18-d9b5.g.aivencloud.com:20198/defaultdb?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false # Enter your Aiven MySQL Password in Render Dashboard
      - key: DB_DRIVER
        value: com.mysql.cj.jdbc.Driver
      - key: JWT_SECRET
        generateValue: true
      - key: HIBERNATE_DDL_AUTO
        value: update
      - key: SQL_INIT_MODE
        value: never
