server:
  port: ${PORT:8080}

spring:
  application:
    name: online-banking
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql-2b7feb4e-mohanboddu18-d9b5.g.aivencloud.com:20198/defaultdb?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:avnadmin}
    password: ${DB_PASSWORD:mohan}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      format_sql: true
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

bank:
  app:
    jwtSecret: ${JWT_SECRET:BankingManagementSuperSecretKey2026GodavariBankSimulationSecureToken9876543210987654321}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000} # 24 Hours
    ifscPrefix: "GDVB"
    branchCode: "000123"
    branchName: "Godavari Bank Main Branch, Rajahmundry"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
